### ISSUE TITLE
Fix Read Memory test for Arch 

### ISSUE THREAD

**Issue by fabiim** [headcrab-rs/headcrab#82]
The readmemory test is failing for me in Arch. 

```

running 4 tests
test target::linux::tests::read_memory ... ok
test target::linux::tests::reads_threads ... ok
test target::linux::tests::read_protected_memory ... ok
test target::linux::tests::read_cross_page_memory ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out


running 1 test
test attach_readmem ... ignored

test result: ok. 0 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out


running 1 test
make: Nothing to be done for 'all'.
test disassemble ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out


running 1 test
make: Nothing to be done for 'all'.
test fixed_breakpoint ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out


running 1 test
make: Nothing to be done for 'all'.
test read_memory ... FAILED

failures:

---- read_memory stdout ----
[
    MemoryMap {
        address: (
            93824992231424,
            93824992251904,
        ),
        backing_file: Some(
            (
                "/home/fabiim/dev/headcrab/tests/testees/hello",
                0,
            ),
        ),
        is_readable: true,
        is_writable: false,
        is_executable: false,
        is_private: true,
    },
    MemoryMap {
        address: (
            93824992251904,
            93824992419840,
        ),
        backing_file: Some(
            (
                "/home/fabiim/dev/headcrab/tests/testees/hello",
                20480,
            ),
        ),
        is_readable: true,
        is_writable: false,
        is_executable: true,
        is_private: true,
    },
    MemoryMap {
        address: (
            93824992419840,
            93824992464896,
        ),
        backing_file: Some(
            (
                "/home/fabiim/dev/headcrab/tests/testees/hello",
                188416,
            ),
        ),
        is_readable: true,
        is_writable: false,
        is_executable: false,
        is_private: true,
    },
    MemoryMap {
        address: (
            93824992468992,
            93824992481280,
        ),
        backing_file: Some(
            (
                "/home/fabiim/dev/headcrab/tests/testees/hello",
                233472,
            ),
        ),
        is_readable: true,
        is_writable: true,
        is_executable: false,
        is_private: true,
    },
    MemoryMap {
        address: (
            140737353920512,
            140737353936896,
        ),
        backing_file: None,
        is_readable: true,
        is_writable: false,
        is_executable: false,
        is_private: true,
    },
    MemoryMap {
        address: (
            140737353936896,
            140737353945088,
        ),
        backing_file: None,
        is_readable: true,
        is_writable: false,
        is_executable: true,
        is_private: true,
    },
    MemoryMap {
        address: (
            140737353945088,
            140737353953280,
        ),
        backing_file: Some(
            (
                "/usr/lib/ld-2.31.so",
                0,
            ),
        ),
        is_readable: true,
        is_writable: false,
        is_executable: false,
        is_private: true,
    },
    MemoryMap {
        address: (
            140737353953280,
            140737354084352,
        ),
        backing_file: Some(
            (
                "/usr/lib/ld-2.31.so",
                8192,
            ),
        ),
        is_readable: true,
        is_writable: false,
        is_executable: true,
        is_private: true,
    },
    MemoryMap {
        address: (
            140737354084352,
            140737354117120,
        ),
        backing_file: Some(
            (
                "/usr/lib/ld-2.31.so",
                139264,
            ),
        ),
        is_readable: true,
        is_writable: false,
        is_executable: false,
        is_private: true,
    },
    MemoryMap {
        address: (
            140737354121216,
            140737354129408,
        ),
        backing_file: Some(
            (
                "/usr/lib/ld-2.31.so",
                172032,
            ),
        ),
        is_readable: true,
        is_writable: true,
        is_executable: false,
        is_private: true,
    },
    MemoryMap {
        address: (
            140737354129408,
            140737354133504,
        ),
        backing_file: None,
        is_readable: true,
        is_writable: true,
        is_executable: false,
        is_private: true,
    },
    MemoryMap {
        address: (
            140737488216064,
            140737488351232,
        ),
        backing_file: None,
        is_readable: true,
        is_writable: true,
        is_executable: false,
        is_private: true,
    },
    MemoryMap {
        address: (
            18446744073699065856,
            18446744073699069952,
        ),
        backing_file: None,
        is_readable: false,
        is_writable: false,
        is_executable: true,
        is_private: true,
    },
]
thread 'read_memory' panicked at 'assertion failed: `(left == right)`
  left: `[46, 15]`,
 right: `[243, 144]`', tests/test_utils.rs:60:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/io/mod.rs:1537
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:176
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:215
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  12: rust_begin_unwind
             at src/libstd/panicking.rs:388
  13: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:342
  14: readmem::test_utils::patch_breakpoint
             at tests/test_utils.rs:60
  15: readmem::read_memory
             at tests/readmem.rs:65
  16: readmem::read_memory::{{closure}}
             at tests/readmem.rs:20
  17: core::ops::function::FnOnce::call_once
             at /home/fabiim/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/function.rs:232
  18: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/liballoc/boxed.rs:1076
  19: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/panic.rs:318
  20: std::panicking::try::do_call
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/panicking.rs:297
  21: std::panicking::try
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/panicking.rs:274
  22: std::panic::catch_unwind
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/panic.rs:394
  23: test::run_test_in_process
             at src/libtest/lib.rs:541
  24: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:450
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    read_memory

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out


```

**Comment by JJendryka** [comment]
Weird. Works for me. I'm also on Arch.

**Comment by bjorn3** [comment]
Can you show the disassembly of the `breakpoint` function in `tests/testees/hello`?

**Comment by fabiim** [comment]
> Can you show the disassembly of the breakpoint function in tests/testees/hello?

Is this enough (from objdump -d ): 

```
00000000000052a0 <breakpoint>:
    52a0:	f3 90                	pause  
    52a2:	c3                   	retq   
    52a3:	66 2e 0f 1f 84 00 00 	nopw   %cs:0x0(%rax,%rax,1)
    52aa:	00 00 00 
    52ad:	0f 1f 00             	nopl   (%rax)

```

**Comment by bjorn3** [comment]
Try removing `tests/testees/hello`. I recently enabled `-Cforce-frame-pointers=yes`, which affects the disassembly of the function. Changing the `Makefile` doesn't rebuild it.

**Comment by fabiim** [comment]
> Try removing tests/testees/hello. I recently enabled -Cforce-frame-pointers=yes, which affects the disassembly of the function. Changing the Makefile doesn't rebuild it.

Ah sorry, should have thought of that. Thank you!
